# SPDX-License-Identifier: MIT
"""Write a small synthetic ACE table carrying an unresolved resonance block.

No ACE file small enough to keep as a fixture has a URR block — the nuclides
that have one are heavy, and their tables run to tens of megabytes, which
cannot be trimmed because JXS holds absolute offsets into XSS. So the block is
built here instead, at a size that fits in a fixture.

The values are invented, but the *layout* is the format's, which is what the
reader is being tested against: JXS(23) points at the block, the block opens
with its dimensions and flags, then the energies in MeV, then N*6*M values with
the heating numbers in row 5 that the reader has to convert.

    python tools/make_urr_ace.py tests/synthetic-urr.ace
"""

from __future__ import annotations

import sys
from pathlib import Path

#: Dimensions of the synthetic block: energies and equiprobable bands.
N_ENERGY = 4
N_BAND = 3

#: Where the URR block starts within XSS (one-based, as JXS is).
URR_START = 21


def urr_block() -> list[float]:
    """The block itself, laid out as the format specifies."""
    values: list[float] = [
        float(N_ENERGY),
        float(N_BAND),
        2.0,  # interpolation: lin-lin
        -1.0,  # inelastic flag: zero across the range
        -1.0,  # absorption flag: likewise
        1.0,  # multiply by the smooth background
    ]
    # Energies in MeV, which the reader converts to eV.
    values += [1.0e-3 * (i + 1) for i in range(N_ENERGY)]

    # N blocks of 6 rows of M bands. Row 5 is the heating number, the one row
    # the reader scales; every value is distinct so a misplaced index shows.
    for e in range(N_ENERGY):
        for q in range(6):
            for b in range(N_BAND):
                values.append(round(1.0 + e + 0.1 * q + 0.01 * b, 6))
    return values


def main() -> None:
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    target = Path(sys.argv[1])

    block = urr_block()
    # XSS runs from index 1; pad up to where the block starts.
    xss = [0.0] * (URR_START - 1) + block
    n_xss = len(xss)

    nxs = [0] * 16
    nxs[0] = n_xss  # NXS(1): length of XSS
    nxs[1] = 92000  # NXS(2): ZA
    nxs[2] = N_ENERGY  # NXS(3): number of energies, unused here

    jxs = [0] * 32
    jxs[22] = URR_START  # JXS(23): start of the URR block

    def fixed(values, width: int, per_line: int, fmt) -> list[str]:
        out = []
        for i in range(0, len(values), per_line):
            out.append("".join(fmt(v).rjust(width) for v in values[i : i + per_line]))
        return out

    lines = [
        f"{'92000.00c':>10}{'236.005800':>12}{'2.5300E-08':>12}   01/01/26",
        f"{'synthetic URR fixture, generated by tools/make_urr_ace.py':<70}mat9200",
    ]
    # Four lines of four (IZ, AW) pairs, all empty for a synthetic table.
    for _ in range(4):
        lines.append("".join(f"{0:>7}{0.0:>11.6f}" for _ in range(4)))
    # NXS and JXS, eight to a line.
    lines += fixed(nxs, 9, 8, lambda v: str(int(v)))
    lines += fixed(jxs, 9, 8, lambda v: str(int(v)))
    # XSS, four to a line.
    lines += fixed(xss, 20, 4, lambda v: f"{v:.11E}")

    target.write_text("\n".join(lines) + "\n")
    print(f"{target}: {n_xss} XSS values, URR block at {URR_START}", file=sys.stderr)


if __name__ == "__main__":
    main()
